# -*- coding: utf-8 -*-
"""main_statistical_evallution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17rmNP7MtMmuXOx3l56288laxV_-hvAqx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# File Path
file_path = "/content/Organised_Data_Sets.xlsx"

# Check Sheet Names
xls = pd.ExcelFile(file_path)

print("Available Sheets:")
print(xls.sheet_names)
df = pd.read_excel(
    file_path,
    sheet_name="statistical_evaluation ",
    header=43,
    usecols="A:H",
    nrows=16
)

# Clean Column Names
df.columns = (
    df.columns
      .astype(str)
      .str.strip()
      .str.replace("\n", " ", regex=False)
)

print("\nDetected Columns:")
print(df.columns.tolist())

# Verify Required Columns Exist
required_columns = [
    "Name of the Conference",
    "Year",
    "Citation Impact Score",
    "Diversity Score",
    "Reference Quality Score",
    "Collaboration Score",
    "Visual Communication Score"
]

missing = [c for c in required_columns if c not in df.columns]

if len(missing) > 0:
    print("\nMissing Columns:")
    print(missing)
    raise ValueError(
        "Column names do not match Excel sheet. "
        "Check printed column names above."
    )

# Calculate ICEI
df["ICEI"] = (
    0.50 * df["Citation Impact Score"] +
    0.15 * df["Diversity Score"] +
    0.15 * df["Reference Quality Score"] +
    0.10 * df["Collaboration Score"] +
    0.10 * df["Visual Communication Score"]
)

df["ICEI"] = df["ICEI"].round(4)

# Save Calculated Values
df.to_excel("ICEI_Calculated.xlsx", index=False)

# Create Pivot Table
pivot_df = df.pivot(
    index="Name of the Conference",
    columns="Year",
    values="ICEI"
)

pivot_df = pivot_df.sort_index()

# Plot
plt.figure(figsize=(8,6))

x = np.arange(len(pivot_df))
width = 0.35

bars_2023 = plt.bar(
    x - width/2,
    pivot_df.get(2023),
    width,
    color="red",
    edgecolor="black",
    label="2023"
)

bars_2024 = plt.bar(
    x + width/2,
    pivot_df.get(2024),
    width,
    color="blue",
    edgecolor="black",
    label="2024"
)

# Value Labels
for bar in bars_2023:
    h = bar.get_height()
    if not np.isnan(h):
        plt.text(
            bar.get_x() + bar.get_width()/2,
            h + 0.01,
            f"{h:.2f}",
            ha="center",
            fontsize=8
        )

for bar in bars_2024:
    h = bar.get_height()
    if not np.isnan(h):
        plt.text(
            bar.get_x() + bar.get_width()/2,
            h + 0.01,
            f"{h:.2f}",
            ha="center",
            fontsize=8
        )

# Formatting
plt.xlabel(
    "Conference",
    fontsize=12,
    fontweight="bold"
)

plt.ylabel(
    "ICEI Score",
    fontsize=12,
    fontweight="bold"
)

plt.title(
    "IoT Conference Excellence Index (ICEI): 2023 vs 2024",
    fontsize=14,
    fontweight="bold"
)

plt.xticks(
    x,
    pivot_df.index,
    rotation=45,
    ha="right"
)

plt.legend()
plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()

plt.savefig(
    "Figure1_ICEI_Grouped_BarChart.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()


# Rankings
rank2023 = (
    df[df["Year"] == 2023]
    [["Name of the Conference", "ICEI"]]
    .sort_values("ICEI", ascending=False)
)

rank2024 = (
    df[df["Year"] == 2024]
    [["Name of the Conference", "ICEI"]]
    .sort_values("ICEI", ascending=False)
)

print("\n ICEI Ranking 2023")
print(rank2023)

print("\n ICEI Ranking 2024")
print(rank2024)

print("\nGenerated Files:")
print("ICEI_Calculated.xlsx")
print("Figure1_ICEI_Grouped_BarChart.png")

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

# Read Excel File
file_path = "/content/Organised_Data_Sets.xlsx"

df = pd.read_excel(
    file_path,
    sheet_name="total_consolidated_data"
)

# Clean Column Names
df.columns = df.columns.str.strip()


# Conferences of Interest
selected_conferences = [
    "SenSys",
    "EWSN",
    "DCOSS-IoT",
    "WF-IoT",
    "BIOTC"
]

df = df[
    df["Conference"].isin(selected_conferences)
]


# Create Conference-Year Label
df["Conference_Year"] = (
    df["Conference"]
    + "-"
    + df["Conference year"].astype(str)
)


# Remove Missing Citation Values
df = df.dropna(
    subset=["Number of citations under Google Scholar"]
)


# Order of Display
conference_order = [
    "BIOTC-2023",
    "BIOTC-2024",
    "DCOSS-IoT-2023",
    "DCOSS-IoT-2024",
    "EWSN-2023",
    "EWSN-2024",
    "SenSys-2023",
    "SenSys-2024",
    "WF-IoT-2023",
    "WF-IoT-2024"
]

box_data = []

for conf in conference_order:

    citations = df[
        df["Conference_Year"] == conf
    ]["Number of citations under Google Scholar"]

    box_data.append(citations)


# Plot
fig, ax = plt.subplots(figsize=(8,6))

bp = ax.boxplot(
    box_data,
    positions=np.arange(1, 11),
    widths=0.6,
    patch_artist=True,
    tick_labels=[""] * len(conference_order),
    showfliers=True
)


# Box Colors
for i, box in enumerate(bp['boxes']):

    if "2023" in conference_order[i]:

        box.set(
            facecolor="lightcoral",
            edgecolor="darkred",
            hatch="//",
            linewidth=1.5
        )

    else:

        box.set(
            facecolor="lightblue",
            edgecolor="navy",
            hatch="\\\\",
            linewidth=1.5
        )


# Median Lines
for median in bp['medians']:
    median.set(
        color='black',
        linewidth=2
    )


# Outlier Markers
for i, flier in enumerate(bp['fliers']):

    if "2023" in conference_order[i]:

        flier.set(
            marker='o',
            markerfacecolor='red',
            markeredgecolor='darkred',
            markersize=6
        )

    else:

        flier.set(
            marker='s',
            markerfacecolor='blue',
            markeredgecolor='navy',
            markersize=6
        )


# Conference Labels (Only Once)
conference_centers = [1.5, 3.5, 5.5, 7.5, 9.5]

conference_labels = [
    "BIOTC",
    "DCOSS-IoT",
    "EWSN",
    "SenSys",
    "WF-IoT"
]

ax.set_xticks(conference_centers)

ax.set_xticklabels(
    conference_labels,
    fontsize=12,
)

# Year Labels Under Each Box
year_labels = [
    "2023", "2024",
    "2023", "2024",
    "2023", "2024",
    "2023", "2024",
    "2023", "2024"
]


# Axis Labels
ax.set_ylabel(
    "Paper Citations",
    fontsize=12,
    fontweight="bold"
)

ax.set_xlabel(
    "Conference",
    fontsize=12,
    fontweight="bold"
)

ax.set_title(
    "Citation Distribution Across Major IoT Conferences",
    fontsize=14,
    fontweight="bold"
)


# Grid
ax.grid(
    axis='y',
    linestyle='--',
    alpha=0.4
)


# Legend
legend_elements = [
    Patch(
        facecolor='lightcoral',
        edgecolor='darkred',
        hatch='//',
        label='2023'
    ),
    Patch(
        facecolor='lightblue',
        edgecolor='navy',
        hatch='\\\\',
        label='2024'
    )
]

ax.legend(
    handles=legend_elements,
    loc='upper right'
)

# Save Figure
plt.tight_layout()

plt.savefig(
    "Figure2_Selected_Conference_Boxplot.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()